# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-05 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='DesignProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=140, null=True)),
                ('potential_solution', models.TextField(max_length=140, null=True)),
                ('profit_opportunities', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('colour', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20)),
                ('completion_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PotentialClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('reason', models.TextField(max_length=140, null=True)),
                ('how_to_get_client', models.TextField(max_length=140, null=True)),
                ('best_way_to_contact', models.CharField(choices=[('email', 'email'), ('Phone Number', 'Phone Number'), ('Social media', 'Social media')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PotentialProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=140, null=True)),
                ('reason', models.TextField(max_length=140, null=True)),
                ('profit_opportunities', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
    ]
