# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170214_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='colour',
        ),
    ]
