# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_job_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designproblems',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='potentialproject',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
