# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-16 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_inspiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date',
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
