# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-19 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20170216_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('blocked', 'blocked'), ('Client Review', 'Client Review')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Job')),
            ],
        ),
    ]
