# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='sdsdfsdf', max_length=40),
            preserve_default=False,
        ),
    ]
