# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-27 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20170227_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='designproblems',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inspiration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='potentialclient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='potentialproject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
