# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-09 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20170227_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='job',
        ),
    ]
