# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-14 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20170314_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='archived_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
