# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-31 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20170314_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('description', models.TextField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='items',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
