# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-31 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_itemprice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprice',
            name='user',
        ),
        migrations.DeleteModel(
            name='ItemPrice',
        ),
    ]
