# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-04 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20170403_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailslog',
            name='host_email',
            field=models.EmailField(default='servicedesk.asotiwa@gmail.com', max_length=30),
            preserve_default=False,
        ),
    ]
