# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-06 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_sentemailslog_host_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailslog',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Client'),
            preserve_default=False,
        ),
    ]
